[[plugins]]
repo = 'Shougo/dein.vim'


#[[plugins]]
#repo = 'Shougo/vimproc'
#
#  [plugins.build]
#  windows = 'tools\\update-dll-mingw'
#  cygwin  = 'make -f make_cygwin.mak'
#  mac     = 'make -f make_mac.mak'
#  linux   = 'make'
#  unix    = 'gmake'


#[[plugins]]
#repo = 'vim-airline/vim-airline'
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'


#color scheme
#[[plugins]]
#repo = 'freeo/vim-kalisi'
#[[plugins]]
#repo = 'mhartington/oceanic-next'
[[plugins]]
repo = 'w0ng/vim-hybrid'
#[[plugins]]
#repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\    'python': ['pylint'],
\    'go': ['gofmt'],
\}
let g:ale_fixers = {
\    'python': ['yapf'],
\    'go': ['goimports'],
\}
" Enable integration with airline.
let g:airline#extensions#ale#enabled = 1
let g:ale_sign_column_always = 1
autocmd FileType go let g:ale_fix_on_save = 1
'''

#by S.N
[[plugins]]
repo = 'shohei1029/bio.nvim'
